# Generated by Django 4.2.4 on 2023-08-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
    ]
