# Generated by Django 4.2.4 on 2023-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='modified',
        ),
        migrations.AddField(
            model_name='userfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='userfiles'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
