# Generated by Django 4.2.4 on 2023-08-23 14:51

import app.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_userfile_title_userfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])]),
        ),
    ]
