# Generated by Django 4.2.4 on 2023-09-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userfile_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='new',
        ),
    ]
